# Generated by Django 3.0.5 on 2023-02-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='no_of_questions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
