# Generated by Django 3.0.5 on 2023-02-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20230225_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='no_of_questions',
        ),
    ]
