# Generated by Django 3.0.5 on 2023-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20230225_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='no_of_questions',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=25),
        ),
    ]
